// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATPz_4XG0Nk9jLSpXINcZbidN3vtpz_TI',
    appId: '1:61772139773:web:db0e9f389e6aa60301c294',
    messagingSenderId: '61772139773',
    projectId: 'note-taking-application-7c5e4',
    authDomain: 'note-taking-application-7c5e4.firebaseapp.com',
    storageBucket: 'note-taking-application-7c5e4.appspot.com',
    measurementId: 'G-C65KELE4FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARE_9uqSPYTVdkRxVWdxoA6_oSFWVYpmU',
    appId: '1:61772139773:android:a68e25fa43e269d401c294',
    messagingSenderId: '61772139773',
    projectId: 'note-taking-application-7c5e4',
    storageBucket: 'note-taking-application-7c5e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFTMMFumgo6M7qZbrZHlOGqNapPLR1m0',
    appId: '1:61772139773:ios:0a7f4626c8e868c501c294',
    messagingSenderId: '61772139773',
    projectId: 'note-taking-application-7c5e4',
    storageBucket: 'note-taking-application-7c5e4.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFTMMFumgo6M7qZbrZHlOGqNapPLR1m0',
    appId: '1:61772139773:ios:3278e8448f8c276901c294',
    messagingSenderId: '61772139773',
    projectId: 'note-taking-application-7c5e4',
    storageBucket: 'note-taking-application-7c5e4.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
